### ISSUE TITLE
Error when trying to add account

### ISSUE THREAD

**Issue by hannahci** [SEE-MOF/pansat#44]
I want to add an account for the provider CopernicusProvider to my pansat-accounts, but get the following error message:

```
>>> from pansat.download import accounts
>>> accounts.add_identity("CopernicusProvider", "hannah.imhof@chalmers.se")
Please enter password for provider 'CopernicusProvider' and username 'hannah.imhof@chalmers.se':
Password: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hannah/Work/Courses/SSDP/Pansat/pansat/pansat/download/accounts.py", line 233, in add_identity
    password_encrypted = encrypt(password)
  File "/home/hannah/Work/Courses/SSDP/Pansat/pansat/pansat/download/accounts.py", line 132, in encrypt
    fernet = Fernet(_PANSAT_SECRET)
  File "/home/hannah/.local/lib/python3.8/site-packages/cryptography/fernet.py", line 34, in __init__
    key = base64.urlsafe_b64decode(key)
  File "/usr/lib/python3.8/base64.py", line 131, in urlsafe_b64decode
    s = _bytes_from_decode_data(s)
  File "/usr/lib/python3.8/base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'
```
The problem might be connected to PANSAT_SECRET not being set in the ``encrypt`` function. I do have an identities.json file in my home directory.

**Comment by hannahci** [comment]
yes, I guess ``authenticate()`` needs to be called before calling the ``encrypt`` functions?
